version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:17"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /tools
    schedule:
      interval: weekly
      day: monday
      time: "07:27"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
      day: monday
      time: "07:37"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "07:47"
      timezone: Europe/Amsterdam
    open-pull-requests-limit: 5
